### PR TITLE
Trying to figure out sequelize mock

### PR DESCRIPTION
**Pull request by SpencerFife**
don't push to master, need feedback

### CODE REVIEW

**Comment by SpencerFife** [comment]
fixed some merging conflicts

**Comment by SpencerFife** [comment]
we can just delete this branch

**Comment by malicemarie** [comment]
Do we still want to merge here? I can approve it unless you want to delete this branch?

**Comment by SpencerFife** [comment]
delete it

**Comment by SpencerFife** [comment]
we're working with a new branch

**Comment by Dragonbabe** [comment]
Decided to to not use mock and spy. Change of plans.

**Pull request closed without merging**
